services:
  app:
    image: flight-diaries-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    volumes:
      - ./frontend:/usr/src/app
    container_name: flight-diaries-frontend

  backend:
    image: flight-diaries-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: flight-diaries-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend
